# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_event_event_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
